### ISSUE TITLE
Ask for the paper

### ISSUE THREAD

**Issue by hustnn** [freuk/predictsim#1]
Hi Freuk:

Is it convenient to give the access URL of your SC 15 paper (Improving Backfilling by using Machine Learning to Predict Running Times ) ?

**Comment by freuk** [comment]
Hi hustnn,
freux.fr/papers/SC15_backfilling_with_ML_runtime_predictions.pdf

cheers :)

Quoting hustnn (2015-09-24 09:50:47)

**Comment by hustnn** [comment]
Thanks very much.
